title: Eduard Stehlík | stehled.com
description:  "stehled's official CV page."
url: https://stehled.github.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
